# Generated by Django 5.1.7 on 2025-04-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='categoria',
            field=models.CharField(choices=[('1ra', 'Primera'), ('2da', 'Segunda'), ('3ra', 'Tercera'), ('3raB', 'Tercera B')], default='3ra', max_length=10),
        ),
    ]
