# Generated by Django 5.2.8 on 2025-11-21 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugadores', '0002_alter_jugador_categoria'),
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('jugada', models.BooleanField(default=False)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas', to='torneos.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='Tanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tandas', to='fechas.fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_ganados', to='jugadores.jugador')),
                ('perdedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_perdidos', to='jugadores.jugador')),
                ('tanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='fechas.tanda')),
            ],
        ),
    ]
