# Generated by Django 5.2.8 on 2026-02-21 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechas', '0001_initial'),
        ('jugadores', '0002_alter_jugador_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanda',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='fecha',
            name='jugada',
        ),
        migrations.AddField(
            model_name='fecha',
            name='club_organizador',
            field=models.CharField(blank=True, choices=[('NEWBERY', 'Newbery'), ('CAI', 'Cai'), ('HURACAN', 'Huracán'), ('SAN_MANUEL', 'San Manuel')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fecha',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveIntegerField()),
                ('puntaje', models.PositiveIntegerField()),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='fechas.fecha')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='jugadores.jugador')),
            ],
            options={
                'unique_together': {('fecha', 'jugador')},
            },
        ),
        migrations.DeleteModel(
            name='Partido',
        ),
        migrations.DeleteModel(
            name='Tanda',
        ),
    ]
